In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd



# Define the file path
file_path = '/content/drive/MyDrive/trainn.csv'  # Replace this with your actual file path

# Load the data into a pandas DataFrame
data = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(data.head())


  GENDER  AGE   WBC  Platelets  Neutrophils  Lymphocytes  Monocytes  \
0      F   70   4.9      145.0          4.0          0.7        0.3   
1      M   61  11.3      166.0         10.7          0.5        0.1   
2      F   70  15.8      202.0         13.9          1.0        0.8   
3      M   85  10.6      227.0          NaN          NaN        NaN   
4      F   89   4.5      170.0          3.8          0.5        0.2   

   Eosinophils  Basophils    CRP    AST   ALT   ALP   GGT    LDH  Class  
0          0.0        0.0   87.9   68.0  41.0  89.0  63.0  606.0      1  
1          0.0        0.0  174.3  118.0  95.0  59.0  77.0  808.0      1  
2          0.0        0.0   43.8   20.0  26.0  80.0  16.0  235.0      0  
3          NaN        NaN    6.3   31.0  16.0   NaN   NaN    NaN      0  
4          0.0        0.0  133.6   57.0  17.0  81.0  19.0  626.0      1  


In [ ]:
data.shape
data.describe()
# Assuming 'data' is your DataFrame
#data.drop_duplicates(inplace=True)


AGE         WBC   Platelets  Neutrophils  Lymphocytes  \
count  279.000000  277.000000  277.000000   209.000000   209.000000   
mean    61.336918    8.553069  226.532130     6.200478     1.182775   
std     18.491523    4.855353  101.174178     4.172581     0.806339   
min      0.000000    1.100000   20.000000     0.500000     0.200000   
25%     49.000000    5.100000  163.000000     3.500000     0.700000   
50%     64.000000    7.100000  205.000000     5.100000     1.000000   
75%     76.000000   10.700000  271.000000     7.500000     1.400000   
max     98.000000   29.200000  620.000000    26.400000     7.200000   

        Monocytes  Eosinophils   Basophils         CRP         AST  \
count  209.000000   209.000000  208.000000  273.000000  277.000000   
mean     0.605742     0.055024    0.014423   90.889011   54.202166   
std      0.410049     0.132237    0.039116   94.421406   57.612797   
min      0.000000     0.000000    0.000000    0.100000   11.000000   
25%      0.400000     0.000000    0.000000   21.400000   27.000000   
50%      0.500000     0.000000    0.000000   54.200000   36.000000   
75%      0.700000     0.100000    0.000000  129.100000   60.000000   
max      3.200000     1.300000    0.300000  478.000000  550.000000   

              ALT         ALP         GGT          LDH       Class  
count  266.000000  131.000000  136.000000   194.000000  279.000000  
mean    44.917293   89.893130   82.477941   380.448454    0.634409  
std     45.503232   89.089864  132.702506   193.983520    0.482461  
min      9.000000   34.000000   10.000000    98.000000    0.000000  
25%     21.000000   57.500000   23.750000   243.250000    0.000000  
50%     31.000000   71.000000   41.000000   328.000000    1.000000  
75%     46.000000   90.000000   83.000000   454.500000    1.000000  
max    335.000000  838.000000  839.000000  1195.000000    1.000000

In [ ]:
data.duplicated()
data.isnull()
data.isnull().sum()



GENDER           0
AGE              0
WBC              2
Platelets        2
Neutrophils     70
Lymphocytes     70
Monocytes       70
Eosinophils     70
Basophils       71
CRP              6
AST              2
ALT             13
ALP            148
GGT            143
LDH             85
Class            0
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Assuming your dataset is stored in a DataFrame named 'data'
x = data[["AGE", "WBC", 'Platelets', 'Neutrophils', 'Lymphocytes', 'Monocytes', 'Eosinophils', 'Basophils', 'CRP', 'AST', 'ALT', 'ALP', 'GGT', 'LDH']].values
y = data[['Class']].values

# Initialize the SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit and transform the imputer on the feature array x
x_imputed = imputer.fit_transform(x)

# The imputer can be applied to any missing values using transform
x_imputed = imputer.transform(x)
x_imputed





array([[ 70.        ,   4.9       , 145.        , ...,  89.        ,
         63.        , 606.        ],
       [ 61.        ,  11.3       , 166.        , ...,  59.        ,
         77.        , 808.        ],
       [ 70.        ,  15.8       , 202.        , ...,  80.        ,
         16.        , 235.        ],
       ...,
       [ 53.        ,   5.3       , 224.        , ...,  89.89312977,
         82.47794118, 263.        ],
       [ 30.        ,   8.2       , 211.        , ...,  56.        ,
         17.        , 209.        ],
       [ 82.        ,   5.1       , 166.        , ...,  58.        ,
         18.        , 524.        ]])

In [ ]:
x=data[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']]
y=data[['Class']]

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']])
imputer

SimpleImputer()

In [ ]:
x[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']]=imputer.fit_transform(x[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']])
x

<ipython-input-8-41a90698cd66>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']]=imputer.fit_transform(x[["AGE","WBC",'Platelets','Neutrophils','Lymphocytes','Monocytes','Eosinophils','Basophils','CRP','AST','ALT','ALP','GGT','LDH']])


AGE   WBC  Platelets  Neutrophils  Lymphocytes  Monocytes  Eosinophils  \
0    70.0   4.9      145.0     4.000000     0.700000   0.300000     0.000000   
1    61.0  11.3      166.0    10.700000     0.500000   0.100000     0.000000   
2    70.0  15.8      202.0    13.900000     1.000000   0.800000     0.000000   
3    85.0  10.6      227.0     6.200478     1.182775   0.605742     0.055024   
4    89.0   4.5      170.0     3.800000     0.500000   0.200000     0.000000   
..    ...   ...        ...          ...          ...        ...          ...   
274  63.0  14.6      202.0    13.000000     0.400000   1.200000     0.000000   
275  89.0  19.7      158.0     6.200478     1.182775   0.605742     0.055024   
276  53.0   5.3      224.0     3.400000     1.400000   0.500000     0.000000   
277  30.0   8.2      211.0     6.200478     1.182775   0.605742     0.055024   
278  82.0   5.1      166.0     6.200478     1.182775   0.605742     0.055024   

     Basophils    CRP    AST   ALT       ALP        GGT         LDH  
0     0.000000   87.9   68.0  41.0  89.00000  63.000000  606.000000  
1     0.000000  174.3  118.0  95.0  59.00000  77.000000  808.000000  
2     0.000000   43.8   20.0  26.0  80.00000  16.000000  235.000000  
3     0.014423    6.3   31.0  16.0  89.89313  82.477941  380.448454  
4     0.000000  133.6   57.0  17.0  81.00000  19.000000  626.000000  
..         ...    ...    ...   ...       ...        ...         ...  
274   0.000000  250.6   65.0  87.0  65.00000  37.000000  416.000000  
275   0.014423    3.0   26.0  17.0  89.89313  82.477941  275.000000  
276   0.000000    7.8   36.0  41.0  89.89313  82.477941  263.000000  
277   0.014423   12.4   35.0  41.0  56.00000  17.000000  209.000000  
278   0.014423  112.6   46.0  17.0  58.00000  18.000000  524.000000  

[279 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train
y_train
x_test
y_test

Class
194      0
78       1
274      1
169      1
41       1
101      0
155      1
159      1
229      1
6        0
218      1
96       1
44       0
241      0
210      1
3        0
232      0
16       0
252      0
54       1
68       1
209      1
219      0
14       0
195      1
83       1
226      1
145      0
205      1
228      1
34       1
212      0
109      0
37       1
62       0
107      0
39       0
77       0
150      1
4        1
15       1
58       0
258      0
61       1
57       1
86       0
131      1
227      0
103      1
230      1
203      1
49       0
225      1
158      0
98       0
108      1

In [ ]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
data['GENDER']= label_encoder.fit_transform(data['GENDER'])
data['GENDER'].unique()

array([0, 1])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lr_model=LogisticRegression()
lr_model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
lr_model.predict(x_test)

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(random_state=24)
rf_model.fit(x_train,y_train)

<ipython-input-35-677012a61b53>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(x_train,y_train)


RandomForestClassifier(random_state=24)

In [ ]:
predictions=rf_model.predict(x_test)
print("accuracy",accuracy_score(y_test,predictions))

accuracy 0.7272727272727273


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.gaussian_process import GaussianProcessClassifier

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_imputed, y, test_size=0.2)



# Initialize classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    KNeighborsClassifier(),
    LogisticRegression(),
    GaussianNB(),
    SVC(kernel='linear'),
    SVC(kernel='rbf'),
    SGDClassifier(),
    MLPClassifier(),
    AdaBoostClassifier(),
    BaggingClassifier(),
    ExtraTreesClassifier(),
    QuadraticDiscriminantAnalysis(),
    GaussianProcessClassifier()
]

# Dictionary to store accuracies
accuracy_dict = {}

# Iterate through each classifier
for clf in classifiers:
    # Train the classifier
    clf.fit(x_train, y_train)

    # Make predictions
    y_pred = clf.predict(x_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Store accuracy in the dictionary
    accuracy_dict[type(clf).__name__] = accuracy

# Print accuracies
for clf_name, acc in accuracy_dict.items():
    print(f"{clf_name}: {acc}")


<ipython-input-16-c14f2a7566d1>:45: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(x_train, y_train)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True

DecisionTreeClassifier: 0.6785714285714286
RandomForestClassifier: 0.8035714285714286
GradientBoostingClassifier: 0.8035714285714286
KNeighborsClassifier: 0.7678571428571429
LogisticRegression: 0.7857142857142857
GaussianNB: 0.6071428571428571
SVC: 0.6428571428571429
SGDClassifier: 0.6964285714285714
MLPClassifier: 0.8035714285714286
AdaBoostClassifier: 0.7321428571428571
BaggingClassifier: 0.7857142857142857
ExtraTreesClassifier: 0.8035714285714286
QuadraticDiscriminantAnalysis: 0.6785714285714286
GaussianProcessClassifier: 0.42857142857142855


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
